//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZIT.AppRouteServer.AppServerAPI.CarInfoManagerService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.firstAid.com/", ConfigurationName="CarInfoManagerService.CarInfoManagerDelegate")]
    public interface CarInfoManagerDelegate {
        
        // CODEGEN: 命名空间  的元素名称 arg0 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        ZIT.AppRouteServer.AppServerAPI.CarInfoManagerService.addCarInfoResponse addCarInfo(ZIT.AppRouteServer.AppServerAPI.CarInfoManagerService.addCarInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="", ReplyAction="*")]
        System.IAsyncResult BeginaddCarInfo(ZIT.AppRouteServer.AppServerAPI.CarInfoManagerService.addCarInfoRequest request, System.AsyncCallback callback, object asyncState);
        
        ZIT.AppRouteServer.AppServerAPI.CarInfoManagerService.addCarInfoResponse EndaddCarInfo(System.IAsyncResult result);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "")]
    public partial class CredentialSoapHeader
    {
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Username;

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string Password;
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addCarInfoRequest {

        [System.ServiceModel.MessageHeaderAttribute(Namespace = "")]
        public ZIT.AppRouteServer.AppServerAPI.CarInfoManagerService.CredentialSoapHeader CredentialSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addCarInfo", Namespace="http://ws.firstAid.com/", Order=0)]
        public ZIT.AppRouteServer.AppServerAPI.CarInfoManagerService.addCarInfoRequestBody Body;
        
        public addCarInfoRequest() {
        }

        public addCarInfoRequest(ZIT.AppRouteServer.AppServerAPI.CarInfoManagerService.CredentialSoapHeader CredentialSoapHeader, ZIT.AppRouteServer.AppServerAPI.CarInfoManagerService.addCarInfoRequestBody Body)
        {
            this.CredentialSoapHeader = CredentialSoapHeader;
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class addCarInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public addCarInfoRequestBody() {
        }
        
        public addCarInfoRequestBody(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addCarInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addCarInfoResponse", Namespace="http://ws.firstAid.com/", Order=0)]
        public ZIT.AppRouteServer.AppServerAPI.CarInfoManagerService.addCarInfoResponseBody Body;
        
        public addCarInfoResponse() {
        }
        
        public addCarInfoResponse(ZIT.AppRouteServer.AppServerAPI.CarInfoManagerService.addCarInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class addCarInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public addCarInfoResponseBody() {
        }
        
        public addCarInfoResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CarInfoManagerDelegateChannel : ZIT.AppRouteServer.AppServerAPI.CarInfoManagerService.CarInfoManagerDelegate, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class addCarInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public addCarInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CarInfoManagerDelegateClient : System.ServiceModel.ClientBase<ZIT.AppRouteServer.AppServerAPI.CarInfoManagerService.CarInfoManagerDelegate>, ZIT.AppRouteServer.AppServerAPI.CarInfoManagerService.CarInfoManagerDelegate {
        
        private BeginOperationDelegate onBeginaddCarInfoDelegate;
        
        private EndOperationDelegate onEndaddCarInfoDelegate;
        
        private System.Threading.SendOrPostCallback onaddCarInfoCompletedDelegate;
        
        public CarInfoManagerDelegateClient() {
        }
        
        public CarInfoManagerDelegateClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CarInfoManagerDelegateClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CarInfoManagerDelegateClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CarInfoManagerDelegateClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<addCarInfoCompletedEventArgs> addCarInfoCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ZIT.AppRouteServer.AppServerAPI.CarInfoManagerService.addCarInfoResponse ZIT.AppRouteServer.AppServerAPI.CarInfoManagerService.CarInfoManagerDelegate.addCarInfo(ZIT.AppRouteServer.AppServerAPI.CarInfoManagerService.addCarInfoRequest request) {
            return base.Channel.addCarInfo(request);
        }

        public string addCarInfo(ZIT.AppRouteServer.AppServerAPI.CarInfoManagerService.CredentialSoapHeader CredentialSoapHeader, string arg0)
        {
            ZIT.AppRouteServer.AppServerAPI.CarInfoManagerService.addCarInfoRequest inValue = new ZIT.AppRouteServer.AppServerAPI.CarInfoManagerService.addCarInfoRequest();
            inValue.Body = new ZIT.AppRouteServer.AppServerAPI.CarInfoManagerService.addCarInfoRequestBody();
            inValue.CredentialSoapHeader = CredentialSoapHeader;
            inValue.Body.arg0 = arg0;
            ZIT.AppRouteServer.AppServerAPI.CarInfoManagerService.addCarInfoResponse retVal = ((ZIT.AppRouteServer.AppServerAPI.CarInfoManagerService.CarInfoManagerDelegate)(this)).addCarInfo(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ZIT.AppRouteServer.AppServerAPI.CarInfoManagerService.CarInfoManagerDelegate.BeginaddCarInfo(ZIT.AppRouteServer.AppServerAPI.CarInfoManagerService.addCarInfoRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginaddCarInfo(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginaddCarInfo(ZIT.AppRouteServer.AppServerAPI.CarInfoManagerService.CredentialSoapHeader CredentialSoapHeader, string arg0, System.AsyncCallback callback, object asyncState)
        {
            ZIT.AppRouteServer.AppServerAPI.CarInfoManagerService.addCarInfoRequest inValue = new ZIT.AppRouteServer.AppServerAPI.CarInfoManagerService.addCarInfoRequest();
            inValue.Body = new ZIT.AppRouteServer.AppServerAPI.CarInfoManagerService.addCarInfoRequestBody();
            inValue.CredentialSoapHeader = CredentialSoapHeader;
            inValue.Body.arg0 = arg0;
            return ((ZIT.AppRouteServer.AppServerAPI.CarInfoManagerService.CarInfoManagerDelegate)(this)).BeginaddCarInfo(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ZIT.AppRouteServer.AppServerAPI.CarInfoManagerService.addCarInfoResponse ZIT.AppRouteServer.AppServerAPI.CarInfoManagerService.CarInfoManagerDelegate.EndaddCarInfo(System.IAsyncResult result) {
            return base.Channel.EndaddCarInfo(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndaddCarInfo(System.IAsyncResult result) {
            ZIT.AppRouteServer.AppServerAPI.CarInfoManagerService.addCarInfoResponse retVal = ((ZIT.AppRouteServer.AppServerAPI.CarInfoManagerService.CarInfoManagerDelegate)(this)).EndaddCarInfo(result);
            return retVal.Body.@return;
        }
        
        private System.IAsyncResult OnBeginaddCarInfo(object[] inValues, System.AsyncCallback callback, object asyncState) {
            ZIT.AppRouteServer.AppServerAPI.CarInfoManagerService.CredentialSoapHeader CredentialSoapHeader = ((ZIT.AppRouteServer.AppServerAPI.CarInfoManagerService.CredentialSoapHeader)(inValues[0]));
            string arg0 = ((string)(inValues[1]));
            return this.BeginaddCarInfo(CredentialSoapHeader,arg0, callback, asyncState);
        }
        
        private object[] OnEndaddCarInfo(System.IAsyncResult result) {
            string retVal = this.EndaddCarInfo(result);
            return new object[] {
                    retVal};
        }
        
        private void OnaddCarInfoCompleted(object state) {
            if ((this.addCarInfoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.addCarInfoCompleted(this, new addCarInfoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }

        public void addCarInfoAsync(ZIT.AppRouteServer.AppServerAPI.CarInfoManagerService.CredentialSoapHeader CredentialSoapHeader, string arg0)
        {
            this.addCarInfoAsync(CredentialSoapHeader,arg0, null);
        }
        
        public void addCarInfoAsync(ZIT.AppRouteServer.AppServerAPI.CarInfoManagerService.CredentialSoapHeader CredentialSoapHeader,string arg0, object userState) {
            if ((this.onBeginaddCarInfoDelegate == null)) {
                this.onBeginaddCarInfoDelegate = new BeginOperationDelegate(this.OnBeginaddCarInfo);
            }
            if ((this.onEndaddCarInfoDelegate == null)) {
                this.onEndaddCarInfoDelegate = new EndOperationDelegate(this.OnEndaddCarInfo);
            }
            if ((this.onaddCarInfoCompletedDelegate == null)) {
                this.onaddCarInfoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnaddCarInfoCompleted);
            }
            base.InvokeAsync(this.onBeginaddCarInfoDelegate, new object[] {
                         CredentialSoapHeader,
                        arg0}, this.onEndaddCarInfoDelegate, this.onaddCarInfoCompletedDelegate, userState);
        }
    }
}
