//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZIT.AppRouteServer.AppServerAPI.CallErrorManagerService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.fristAid.com/", ConfigurationName="CallErrorManagerService.CallErrorManagerDelegate")]
    public interface CallErrorManagerDelegate {
        
        // CODEGEN: 命名空间  的元素名称 arg0 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        ZIT.AppRouteServer.AppServerAPI.CallErrorManagerService.addCallErrorResponse addCallError(ZIT.AppRouteServer.AppServerAPI.CallErrorManagerService.addCallErrorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="", ReplyAction="*")]
        System.IAsyncResult BeginaddCallError(ZIT.AppRouteServer.AppServerAPI.CallErrorManagerService.addCallErrorRequest request, System.AsyncCallback callback, object asyncState);
        
        ZIT.AppRouteServer.AppServerAPI.CallErrorManagerService.addCallErrorResponse EndaddCallError(System.IAsyncResult result);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "")]
    public partial class CredentialSoapHeader
    {
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Username;

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string Password;
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addCallErrorRequest {

        [System.ServiceModel.MessageHeaderAttribute(Namespace = "")]
        public ZIT.AppRouteServer.AppServerAPI.CallErrorManagerService.CredentialSoapHeader CredentialSoapHeader;

        [System.ServiceModel.MessageBodyMemberAttribute(Name="addCallError", Namespace="http://ws.fristAid.com/", Order=0)]
        public ZIT.AppRouteServer.AppServerAPI.CallErrorManagerService.addCallErrorRequestBody Body;
        
        public addCallErrorRequest() {
        }

        public addCallErrorRequest(ZIT.AppRouteServer.AppServerAPI.CallErrorManagerService.CredentialSoapHeader CredentialSoapHeader, ZIT.AppRouteServer.AppServerAPI.CallErrorManagerService.addCallErrorRequestBody Body)
        {
            this.CredentialSoapHeader = CredentialSoapHeader;
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class addCallErrorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public addCallErrorRequestBody() {
        }
        
        public addCallErrorRequestBody(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addCallErrorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addCallErrorResponse", Namespace="http://ws.fristAid.com/", Order=0)]
        public ZIT.AppRouteServer.AppServerAPI.CallErrorManagerService.addCallErrorResponseBody Body;
        
        public addCallErrorResponse() {
        }
        
        public addCallErrorResponse(ZIT.AppRouteServer.AppServerAPI.CallErrorManagerService.addCallErrorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class addCallErrorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public addCallErrorResponseBody() {
        }
        
        public addCallErrorResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CallErrorManagerDelegateChannel : ZIT.AppRouteServer.AppServerAPI.CallErrorManagerService.CallErrorManagerDelegate, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class addCallErrorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public addCallErrorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CallErrorManagerDelegateClient : System.ServiceModel.ClientBase<ZIT.AppRouteServer.AppServerAPI.CallErrorManagerService.CallErrorManagerDelegate>, ZIT.AppRouteServer.AppServerAPI.CallErrorManagerService.CallErrorManagerDelegate {
        
        private BeginOperationDelegate onBeginaddCallErrorDelegate;
        
        private EndOperationDelegate onEndaddCallErrorDelegate;
        
        private System.Threading.SendOrPostCallback onaddCallErrorCompletedDelegate;
        
        public CallErrorManagerDelegateClient() {
        }
        
        public CallErrorManagerDelegateClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CallErrorManagerDelegateClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CallErrorManagerDelegateClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CallErrorManagerDelegateClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<addCallErrorCompletedEventArgs> addCallErrorCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ZIT.AppRouteServer.AppServerAPI.CallErrorManagerService.addCallErrorResponse ZIT.AppRouteServer.AppServerAPI.CallErrorManagerService.CallErrorManagerDelegate.addCallError(ZIT.AppRouteServer.AppServerAPI.CallErrorManagerService.addCallErrorRequest request) {
            return base.Channel.addCallError(request);
        }

        public string addCallError(ZIT.AppRouteServer.AppServerAPI.CallErrorManagerService.CredentialSoapHeader CredentialSoapHeader, string arg0)
        {
            ZIT.AppRouteServer.AppServerAPI.CallErrorManagerService.addCallErrorRequest inValue = new ZIT.AppRouteServer.AppServerAPI.CallErrorManagerService.addCallErrorRequest();
            inValue.Body = new ZIT.AppRouteServer.AppServerAPI.CallErrorManagerService.addCallErrorRequestBody();
            inValue.CredentialSoapHeader = CredentialSoapHeader;
            inValue.Body.arg0 = arg0;
            ZIT.AppRouteServer.AppServerAPI.CallErrorManagerService.addCallErrorResponse retVal = ((ZIT.AppRouteServer.AppServerAPI.CallErrorManagerService.CallErrorManagerDelegate)(this)).addCallError(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ZIT.AppRouteServer.AppServerAPI.CallErrorManagerService.CallErrorManagerDelegate.BeginaddCallError(ZIT.AppRouteServer.AppServerAPI.CallErrorManagerService.addCallErrorRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginaddCallError(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginaddCallError(ZIT.AppRouteServer.AppServerAPI.CallErrorManagerService.CredentialSoapHeader CredentialSoapHeader, string arg0, System.AsyncCallback callback, object asyncState)
        {
            ZIT.AppRouteServer.AppServerAPI.CallErrorManagerService.addCallErrorRequest inValue = new ZIT.AppRouteServer.AppServerAPI.CallErrorManagerService.addCallErrorRequest();
            inValue.Body = new ZIT.AppRouteServer.AppServerAPI.CallErrorManagerService.addCallErrorRequestBody();
            inValue.CredentialSoapHeader = CredentialSoapHeader;
            inValue.Body.arg0 = arg0;
            return ((ZIT.AppRouteServer.AppServerAPI.CallErrorManagerService.CallErrorManagerDelegate)(this)).BeginaddCallError(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ZIT.AppRouteServer.AppServerAPI.CallErrorManagerService.addCallErrorResponse ZIT.AppRouteServer.AppServerAPI.CallErrorManagerService.CallErrorManagerDelegate.EndaddCallError(System.IAsyncResult result) {
            return base.Channel.EndaddCallError(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndaddCallError(System.IAsyncResult result) {
            ZIT.AppRouteServer.AppServerAPI.CallErrorManagerService.addCallErrorResponse retVal = ((ZIT.AppRouteServer.AppServerAPI.CallErrorManagerService.CallErrorManagerDelegate)(this)).EndaddCallError(result);
            return retVal.Body.@return;
        }

        private System.IAsyncResult OnBeginaddCallError( object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            ZIT.AppRouteServer.AppServerAPI.CallErrorManagerService.CredentialSoapHeader CredentialSoapHeader = ((ZIT.AppRouteServer.AppServerAPI.CallErrorManagerService.CredentialSoapHeader)(inValues[0]));
            string arg0 = ((string)(inValues[1]));
            return this.BeginaddCallError(CredentialSoapHeader,arg0, callback, asyncState);
        }
        
        private object[] OnEndaddCallError(System.IAsyncResult result) {
            string retVal = this.EndaddCallError(result);
            return new object[] {
                    retVal};
        }
        
        private void OnaddCallErrorCompleted(object state) {
            if ((this.addCallErrorCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.addCallErrorCompleted(this, new addCallErrorCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void addCallErrorAsync(ZIT.AppRouteServer.AppServerAPI.CallErrorManagerService.CredentialSoapHeader CredentialSoapHeader,string arg0) {
            this.addCallErrorAsync(CredentialSoapHeader,arg0, null);
        }
        
        public void addCallErrorAsync(ZIT.AppRouteServer.AppServerAPI.CallErrorManagerService.CredentialSoapHeader CredentialSoapHeader,string arg0, object userState) {
            if ((this.onBeginaddCallErrorDelegate == null)) {
                this.onBeginaddCallErrorDelegate = new BeginOperationDelegate(this.OnBeginaddCallError);
            }
            if ((this.onEndaddCallErrorDelegate == null)) {
                this.onEndaddCallErrorDelegate = new EndOperationDelegate(this.OnEndaddCallError);
            }
            if ((this.onaddCallErrorCompletedDelegate == null)) {
                this.onaddCallErrorCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnaddCallErrorCompleted);
            }
            base.InvokeAsync(this.onBeginaddCallErrorDelegate, new object[] {
                        CredentialSoapHeader,
                        arg0}, this.onEndaddCallErrorDelegate, this.onaddCallErrorCompletedDelegate, userState);
        }
    }
}
