//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZIT.AppRouteServer.AppServerAPI.CarLocationManagerService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.firstAid.com/", ConfigurationName="CarLocationManagerService.CarLocationManagerDelegate")]
    public interface CarLocationManagerDelegate {
        
        // CODEGEN: 命名空间  的元素名称 arg0 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        ZIT.AppRouteServer.AppServerAPI.CarLocationManagerService.addCarLocationResponse addCarLocation(ZIT.AppRouteServer.AppServerAPI.CarLocationManagerService.addCarLocationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="", ReplyAction="*")]
        System.IAsyncResult BeginaddCarLocation(ZIT.AppRouteServer.AppServerAPI.CarLocationManagerService.addCarLocationRequest request, System.AsyncCallback callback, object asyncState);
        
        ZIT.AppRouteServer.AppServerAPI.CarLocationManagerService.addCarLocationResponse EndaddCarLocation(System.IAsyncResult result);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "")]
    public partial class CredentialSoapHeader
    {
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Username;

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string Password;
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addCarLocationRequest {

        [System.ServiceModel.MessageHeaderAttribute(Namespace = "")]
        public ZIT.AppRouteServer.AppServerAPI.CarLocationManagerService.CredentialSoapHeader CredentialSoapHeader;

        [System.ServiceModel.MessageBodyMemberAttribute(Name="addCarLocation", Namespace="http://ws.firstAid.com/", Order=0)]
        public ZIT.AppRouteServer.AppServerAPI.CarLocationManagerService.addCarLocationRequestBody Body;
        
        public addCarLocationRequest() {
        }

        public addCarLocationRequest(ZIT.AppRouteServer.AppServerAPI.CarLocationManagerService.CredentialSoapHeader CredentialSoapHeader, ZIT.AppRouteServer.AppServerAPI.CarLocationManagerService.addCarLocationRequestBody Body)
        {
            this.CredentialSoapHeader = CredentialSoapHeader;
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class addCarLocationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public addCarLocationRequestBody() {
        }
        
        public addCarLocationRequestBody(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addCarLocationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addCarLocationResponse", Namespace="http://ws.firstAid.com/", Order=0)]
        public ZIT.AppRouteServer.AppServerAPI.CarLocationManagerService.addCarLocationResponseBody Body;
        
        public addCarLocationResponse() {
        }
        
        public addCarLocationResponse(ZIT.AppRouteServer.AppServerAPI.CarLocationManagerService.addCarLocationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class addCarLocationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public addCarLocationResponseBody() {
        }
        
        public addCarLocationResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CarLocationManagerDelegateChannel : ZIT.AppRouteServer.AppServerAPI.CarLocationManagerService.CarLocationManagerDelegate, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class addCarLocationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public addCarLocationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CarLocationManagerDelegateClient : System.ServiceModel.ClientBase<ZIT.AppRouteServer.AppServerAPI.CarLocationManagerService.CarLocationManagerDelegate>, ZIT.AppRouteServer.AppServerAPI.CarLocationManagerService.CarLocationManagerDelegate {
        
        private BeginOperationDelegate onBeginaddCarLocationDelegate;
        
        private EndOperationDelegate onEndaddCarLocationDelegate;
        
        private System.Threading.SendOrPostCallback onaddCarLocationCompletedDelegate;
        
        public CarLocationManagerDelegateClient() {
        }
        
        public CarLocationManagerDelegateClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CarLocationManagerDelegateClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CarLocationManagerDelegateClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CarLocationManagerDelegateClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<addCarLocationCompletedEventArgs> addCarLocationCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ZIT.AppRouteServer.AppServerAPI.CarLocationManagerService.addCarLocationResponse ZIT.AppRouteServer.AppServerAPI.CarLocationManagerService.CarLocationManagerDelegate.addCarLocation(ZIT.AppRouteServer.AppServerAPI.CarLocationManagerService.addCarLocationRequest request) {
            return base.Channel.addCarLocation(request);
        }

        public string addCarLocation(ZIT.AppRouteServer.AppServerAPI.CarLocationManagerService.CredentialSoapHeader CredentialSoapHeader, string arg0)
        {
            ZIT.AppRouteServer.AppServerAPI.CarLocationManagerService.addCarLocationRequest inValue = new ZIT.AppRouteServer.AppServerAPI.CarLocationManagerService.addCarLocationRequest();
            inValue.Body = new ZIT.AppRouteServer.AppServerAPI.CarLocationManagerService.addCarLocationRequestBody();
            inValue.CredentialSoapHeader = CredentialSoapHeader;
            inValue.Body.arg0 = arg0;
            ZIT.AppRouteServer.AppServerAPI.CarLocationManagerService.addCarLocationResponse retVal = ((ZIT.AppRouteServer.AppServerAPI.CarLocationManagerService.CarLocationManagerDelegate)(this)).addCarLocation(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ZIT.AppRouteServer.AppServerAPI.CarLocationManagerService.CarLocationManagerDelegate.BeginaddCarLocation(ZIT.AppRouteServer.AppServerAPI.CarLocationManagerService.addCarLocationRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginaddCarLocation(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginaddCarLocation(ZIT.AppRouteServer.AppServerAPI.CarLocationManagerService.CredentialSoapHeader CredentialSoapHeader, string arg0, System.AsyncCallback callback, object asyncState)
        {
            ZIT.AppRouteServer.AppServerAPI.CarLocationManagerService.addCarLocationRequest inValue = new ZIT.AppRouteServer.AppServerAPI.CarLocationManagerService.addCarLocationRequest();
            inValue.Body = new ZIT.AppRouteServer.AppServerAPI.CarLocationManagerService.addCarLocationRequestBody();
            inValue.CredentialSoapHeader = CredentialSoapHeader;
            inValue.Body.arg0 = arg0;
            return ((ZIT.AppRouteServer.AppServerAPI.CarLocationManagerService.CarLocationManagerDelegate)(this)).BeginaddCarLocation(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ZIT.AppRouteServer.AppServerAPI.CarLocationManagerService.addCarLocationResponse ZIT.AppRouteServer.AppServerAPI.CarLocationManagerService.CarLocationManagerDelegate.EndaddCarLocation(System.IAsyncResult result) {
            return base.Channel.EndaddCarLocation(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndaddCarLocation(System.IAsyncResult result) {
            ZIT.AppRouteServer.AppServerAPI.CarLocationManagerService.addCarLocationResponse retVal = ((ZIT.AppRouteServer.AppServerAPI.CarLocationManagerService.CarLocationManagerDelegate)(this)).EndaddCarLocation(result);
            return retVal.Body.@return;
        }
        
        private System.IAsyncResult OnBeginaddCarLocation(object[] inValues, System.AsyncCallback callback, object asyncState) {
            ZIT.AppRouteServer.AppServerAPI.CarLocationManagerService.CredentialSoapHeader CredentialSoapHeader = ((ZIT.AppRouteServer.AppServerAPI.CarLocationManagerService.CredentialSoapHeader)(inValues[0]));
            string arg0 = ((string)(inValues[1]));
            return this.BeginaddCarLocation(CredentialSoapHeader,arg0, callback, asyncState);
        }
        
        private object[] OnEndaddCarLocation(System.IAsyncResult result) {
            string retVal = this.EndaddCarLocation(result);
            return new object[] {
                    retVal};
        }
        
        private void OnaddCarLocationCompleted(object state) {
            if ((this.addCarLocationCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.addCarLocationCompleted(this, new addCarLocationCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }

        public void addCarLocationAsync(ZIT.AppRouteServer.AppServerAPI.CarLocationManagerService.CredentialSoapHeader CredentialSoapHeader, string arg0)
        {
            this.addCarLocationAsync(CredentialSoapHeader,arg0, null);
        }

        public void addCarLocationAsync(ZIT.AppRouteServer.AppServerAPI.CarLocationManagerService.CredentialSoapHeader CredentialSoapHeader, string arg0, object userState)
        {
            if ((this.onBeginaddCarLocationDelegate == null)) {
                this.onBeginaddCarLocationDelegate = new BeginOperationDelegate(this.OnBeginaddCarLocation);
            }
            if ((this.onEndaddCarLocationDelegate == null)) {
                this.onEndaddCarLocationDelegate = new EndOperationDelegate(this.OnEndaddCarLocation);
            }
            if ((this.onaddCarLocationCompletedDelegate == null)) {
                this.onaddCarLocationCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnaddCarLocationCompleted);
            }
            base.InvokeAsync(this.onBeginaddCarLocationDelegate, new object[] {
                        CredentialSoapHeader,
                        arg0}, this.onEndaddCarLocationDelegate, this.onaddCarLocationCompletedDelegate, userState);
        }
    }
}
