//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZIT.AppRouteServer.AppServerAPI.QualityInfoManagerService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.firstAid.com/", ConfigurationName="QualityInfoManagerService.QualityInfoManagerDelegate")]
    public interface QualityInfoManagerDelegate {
        
        // CODEGEN: 命名空间  的元素名称 arg0 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        ZIT.AppRouteServer.AppServerAPI.QualityInfoManagerService.addQualityInfoResponse addQualityInfo(ZIT.AppRouteServer.AppServerAPI.QualityInfoManagerService.addQualityInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="", ReplyAction="*")]
        System.IAsyncResult BeginaddQualityInfo(ZIT.AppRouteServer.AppServerAPI.QualityInfoManagerService.addQualityInfoRequest request, System.AsyncCallback callback, object asyncState);
        
        ZIT.AppRouteServer.AppServerAPI.QualityInfoManagerService.addQualityInfoResponse EndaddQualityInfo(System.IAsyncResult result);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "")]
    public partial class CredentialSoapHeader
    {
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Username;

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string Password;
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addQualityInfoRequest {

        [System.ServiceModel.MessageHeaderAttribute(Namespace = "")]
        public ZIT.AppRouteServer.AppServerAPI.QualityInfoManagerService.CredentialSoapHeader CredentialSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addQualityInfo", Namespace="http://ws.firstAid.com/", Order=0)]
        public ZIT.AppRouteServer.AppServerAPI.QualityInfoManagerService.addQualityInfoRequestBody Body;
        
        public addQualityInfoRequest() {
        }

        public addQualityInfoRequest(ZIT.AppRouteServer.AppServerAPI.QualityInfoManagerService.CredentialSoapHeader CredentialSoapHeader, ZIT.AppRouteServer.AppServerAPI.QualityInfoManagerService.addQualityInfoRequestBody Body)
        {
            this.CredentialSoapHeader = CredentialSoapHeader;
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class addQualityInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public addQualityInfoRequestBody() {
        }
        
        public addQualityInfoRequestBody(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addQualityInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addQualityInfoResponse", Namespace="http://ws.firstAid.com/", Order=0)]
        public ZIT.AppRouteServer.AppServerAPI.QualityInfoManagerService.addQualityInfoResponseBody Body;
        
        public addQualityInfoResponse() {
        }
        
        public addQualityInfoResponse(ZIT.AppRouteServer.AppServerAPI.QualityInfoManagerService.addQualityInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class addQualityInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public addQualityInfoResponseBody() {
        }
        
        public addQualityInfoResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface QualityInfoManagerDelegateChannel : ZIT.AppRouteServer.AppServerAPI.QualityInfoManagerService.QualityInfoManagerDelegate, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class addQualityInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public addQualityInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QualityInfoManagerDelegateClient : System.ServiceModel.ClientBase<ZIT.AppRouteServer.AppServerAPI.QualityInfoManagerService.QualityInfoManagerDelegate>, ZIT.AppRouteServer.AppServerAPI.QualityInfoManagerService.QualityInfoManagerDelegate {
        
        private BeginOperationDelegate onBeginaddQualityInfoDelegate;
        
        private EndOperationDelegate onEndaddQualityInfoDelegate;
        
        private System.Threading.SendOrPostCallback onaddQualityInfoCompletedDelegate;
        
        public QualityInfoManagerDelegateClient() {
        }
        
        public QualityInfoManagerDelegateClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QualityInfoManagerDelegateClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QualityInfoManagerDelegateClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QualityInfoManagerDelegateClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<addQualityInfoCompletedEventArgs> addQualityInfoCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ZIT.AppRouteServer.AppServerAPI.QualityInfoManagerService.addQualityInfoResponse ZIT.AppRouteServer.AppServerAPI.QualityInfoManagerService.QualityInfoManagerDelegate.addQualityInfo(ZIT.AppRouteServer.AppServerAPI.QualityInfoManagerService.addQualityInfoRequest request) {
            return base.Channel.addQualityInfo(request);
        }

        public string addQualityInfo(ZIT.AppRouteServer.AppServerAPI.QualityInfoManagerService.CredentialSoapHeader CredentialSoapHeader, string arg0)
        {
            ZIT.AppRouteServer.AppServerAPI.QualityInfoManagerService.addQualityInfoRequest inValue = new ZIT.AppRouteServer.AppServerAPI.QualityInfoManagerService.addQualityInfoRequest();
            inValue.Body = new ZIT.AppRouteServer.AppServerAPI.QualityInfoManagerService.addQualityInfoRequestBody();
            inValue.CredentialSoapHeader = CredentialSoapHeader;
            inValue.Body.arg0 = arg0;
            ZIT.AppRouteServer.AppServerAPI.QualityInfoManagerService.addQualityInfoResponse retVal = ((ZIT.AppRouteServer.AppServerAPI.QualityInfoManagerService.QualityInfoManagerDelegate)(this)).addQualityInfo(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ZIT.AppRouteServer.AppServerAPI.QualityInfoManagerService.QualityInfoManagerDelegate.BeginaddQualityInfo(ZIT.AppRouteServer.AppServerAPI.QualityInfoManagerService.addQualityInfoRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginaddQualityInfo(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginaddQualityInfo(ZIT.AppRouteServer.AppServerAPI.QualityInfoManagerService.CredentialSoapHeader CredentialSoapHeader, string arg0, System.AsyncCallback callback, object asyncState)
        {
            ZIT.AppRouteServer.AppServerAPI.QualityInfoManagerService.addQualityInfoRequest inValue = new ZIT.AppRouteServer.AppServerAPI.QualityInfoManagerService.addQualityInfoRequest();
            inValue.Body = new ZIT.AppRouteServer.AppServerAPI.QualityInfoManagerService.addQualityInfoRequestBody();
            inValue.CredentialSoapHeader = CredentialSoapHeader;
            inValue.Body.arg0 = arg0;
            return ((ZIT.AppRouteServer.AppServerAPI.QualityInfoManagerService.QualityInfoManagerDelegate)(this)).BeginaddQualityInfo(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ZIT.AppRouteServer.AppServerAPI.QualityInfoManagerService.addQualityInfoResponse ZIT.AppRouteServer.AppServerAPI.QualityInfoManagerService.QualityInfoManagerDelegate.EndaddQualityInfo(System.IAsyncResult result) {
            return base.Channel.EndaddQualityInfo(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndaddQualityInfo(System.IAsyncResult result) {
            ZIT.AppRouteServer.AppServerAPI.QualityInfoManagerService.addQualityInfoResponse retVal = ((ZIT.AppRouteServer.AppServerAPI.QualityInfoManagerService.QualityInfoManagerDelegate)(this)).EndaddQualityInfo(result);
            return retVal.Body.@return;
        }
        
        private System.IAsyncResult OnBeginaddQualityInfo(object[] inValues, System.AsyncCallback callback, object asyncState) {
            ZIT.AppRouteServer.AppServerAPI.QualityInfoManagerService.CredentialSoapHeader CredentialSoapHeader = ((ZIT.AppRouteServer.AppServerAPI.QualityInfoManagerService.CredentialSoapHeader)(inValues[0]));
            string arg0 = ((string)(inValues[1]));
            return this.BeginaddQualityInfo(CredentialSoapHeader, arg0, callback, asyncState);
        }
        
        private object[] OnEndaddQualityInfo(System.IAsyncResult result) {
            string retVal = this.EndaddQualityInfo(result);
            return new object[] {
                    retVal};
        }
        
        private void OnaddQualityInfoCompleted(object state) {
            if ((this.addQualityInfoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.addQualityInfoCompleted(this, new addQualityInfoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }

        public void addQualityInfoAsync(ZIT.AppRouteServer.AppServerAPI.QualityInfoManagerService.CredentialSoapHeader CredentialSoapHeader, string arg0)
        {
            this.addQualityInfoAsync(CredentialSoapHeader, arg0, null);
        }

        public void addQualityInfoAsync(ZIT.AppRouteServer.AppServerAPI.QualityInfoManagerService.CredentialSoapHeader CredentialSoapHeader, string arg0, object userState)
        {
            if ((this.onBeginaddQualityInfoDelegate == null)) {
                this.onBeginaddQualityInfoDelegate = new BeginOperationDelegate(this.OnBeginaddQualityInfo);
            }
            if ((this.onEndaddQualityInfoDelegate == null)) {
                this.onEndaddQualityInfoDelegate = new EndOperationDelegate(this.OnEndaddQualityInfo);
            }
            if ((this.onaddQualityInfoCompletedDelegate == null)) {
                this.onaddQualityInfoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnaddQualityInfoCompleted);
            }
            base.InvokeAsync(this.onBeginaddQualityInfoDelegate, new object[] {
                         CredentialSoapHeader, 
                        arg0}, this.onEndaddQualityInfoDelegate, this.onaddQualityInfoCompletedDelegate, userState);
        }
    }
}
